### ISSUE TITLE
Чтение по умолчанию

### ISSUE THREAD

**Issue by vvollo** [instead-hub/metaparser#11]
Сейчас команды "осмотреть книгу" и "читать книгу" делают одно и то же. Чтобы вызвать обработчик Consult, нужно вводить "читать в книге про <что-то>", что неудобно, т.к. игрок может не догадаться ввести это.
В принципе, в игре это можно обойти через костыль:
```
VerbRemove "#Consult"
Verb {
	"#Read",
	"[|про|по]чита/ть,проч/есть",
	"в|во {noun}/пр,2 о|об|обо|про * : Consult",
	"~ о|об|обо|про * в|во {noun}/пр,2 : Consult reverse",
	"~ {noun}/вн : Consult",
}
function mp:after_Consult(s, o)
	if not o then
		mp:xaction('Exam', s)
		return
	end
	mp:message 'Consult.CONSULT'
end
```
Но было бы неплохо, если бы такое было непосредственно в МП.

**Comment by gl00my** [comment]
Отвечу по #11 и по #12 здесь.
Библиотека МП 1 в 1 (практически) повторяет библиотеку inform6. Это было сделано ради ускорения разработки, чтобы не набивать свои шишки, а пытаться учесть опыт других людей. Кроме того, идея была в том, чтобы не ломать совместимость для уже написанных игр.

Однако, действительно, есть много моментов, которые хотелось бы улучшить. Но я не хотел бы менять текущую библиотеку МП. Лучше создавать альтернативную "новую" библиотеку. В этой библиотеке уже можно не задумываться о совместимости и экспериментировать. Конечно, эти эксперименты лучше подкреплять играми.

Поэтому, я предлагаю сделать один issue - назвать его "улучшения стандартной библиотеки" и писать все туда. Я же, если/когда дойду до написания этой библиотеки, попытаюсь это учесть. Ну либо кто-то ещё может начать делать свою версию библиотеки.

**Comment by vvollo** [comment]
Ясно, спасибо. Не знал про эту цель
