### ISSUE TITLE
Реакции для вспомогательных объектов при резании, копании, привязывании

### ISSUE THREAD

**Issue by vvollo** [instead-hub/metaparser#12]
Для команд:
* резать объект А объектом Б
* копать объект А объектом Б
* привязать объект А к объекту Б

прописаны обработчики для объекта А, но не для объекта Б. Может быть неудобно, если хочется прописать для объекта Б некую реакцию по умолчанию.
Т.е. нужен аналог ThrownAt/Recieve для действий резать/копать/привязать (возможно, и для других, но мне не хватало именно этих).

**Comment by gl00my** [comment]
См комментарий к #12

Кстати, можно определить game:before_Any и реализовать там перехват каких угодно событий, вызывая нужный метод у страдательных объектов.

**Comment by vvollo** [comment]
Спасибо, попробую
