### ISSUE TITLE
Снимать атрибут "concealed" если объект был взят

### ISSUE THREAD

**Issue by fireton** [instead-hub/metaparser#15]
Ну это просто логично. Потому что если его потом положить, то он «потеряется».

Это для тех объектов, которые можно взять, они присутствуют на сцене, но их надо как-то «проявить» другими действиями игрока.

**Comment by gl00my** [comment]
concealed может быть приёмом. Например, невидимые но подразумеваемые объекты. Потерять объект можно просто, если автор например неправильно описал контейнер (без content или return true).
В общем на мой взгляд потенциально опасное изменение.
Я предлагаю для такого рода экспериментов сделать альтернативную реализацию библиотеки и развивать её как дополнительную.

**Comment by gl00my** [comment]
А как в inform с этим, можешь посмотреть?

**Comment by fireton** [comment]
В информе таки да. Все объекты, попадающие к игроку, перестают быть concealed.
`objectloop (i in player) give i moved ~concealed;`
Это, кстати, в главном цикле вызывается прям каждый ход. Но мне кажется, в МП это можно реализовать в `move`. Просто проверять, что перемещаем в игрока и снимать атрибут.

**Comment by gl00my** [comment]
Тогда нужно подумать.

**Comment by gl00my** [comment]
Пушнул в move :attr'~concealed' прошу проверить

**Comment by vvollo** [comment]
Гардероб в 17 комнатах от этого точно поломается. Там надетая одежда становится невидимой за пределами гардероба.
И еще есть предметы в инвентаре, невидимые всегда.

Короче, библиотеку МП в игре лучше теперь не обновлять)

**Comment by gl00my** [comment]
> Там надетая одежда становится невидимой за пределами гардероба.
По идее не должна. Concealed снимается только в момент когда игрок берёт предмет командой. Можешь это проверить?

**Comment by gl00my** [comment]
То-есть, вот в сам момент когда предмет попадает в плеера, в этот момент concealed снимается (иначе действительно странно, предмета не будет видно в инвентаре). Но потом больше ничего не делается.

**Comment by vvollo** [comment]
Нет, меня неправильно поняли.
"Там надетая одежда становится невидимой за пределами гардероба." - это верное поведение.

**Comment by gl00my** [comment]
> "Там надетая одежда становится невидимой за пределами гардероба." 
Ну пусть она становится невидимой, поясни как моя правка это сломала?

**Comment by gl00my** [comment]
То есть, ну вышел игрок из комнаты. Код поставил concealed. Ну и ок. Это по прежнему должно работать.

**Comment by vvollo** [comment]
Я проверил, вроде ничего не сломалось. Прошу прощения.

**Comment by gl00my** [comment]
> И еще есть предметы в инвентаре, невидимые всегда.

Вот это самое интересное. Как они попадают? Игрок же не берёт их явно? Наверное, на старте игры это делается?

**Comment by gl00my** [comment]
Поговорил с @vvollo и вроде там всё ок.
Но он мне сказал интересную вещь. В МП есть ещё средство, когда мы хотим убрать описание предмета со сцены. Это dsc = false. В таком случае и на сцене предмет не виден, и в инвентаре не пропадает.

Сброс concealed во время взятия предмета, таким образом, имеет смысл только в плане совместимости с информом.

В общем, давайте ещё раз всё взвесим. Оставляем такое поведение?

**Comment by gl00my** [comment]
Да, поведение правильное. Потому что concealed может использоваться для художественности в том числе. Типа: вы стоите на цветочной поляне. Цветок тут удобно делать concealed. После того, как ты его взял, его можно бросить и в этот момент хорошо бы, чтобы он стал видимым. Так что всё ок, оставляю.
