### ISSUE TITLE
when_open у контейнера

### ISSUE THREAD

**Issue by Irremann** [instead-hub/metaparser#5]
obj {
	-"кейс";
	nam = "кейс";
	when_closed = "Массивный стальной кейс.";
	when_open = "Кейс стоит нараспашку.";
	obj = {'предмет'};
	with_key = 'ключ';
}:attr 'static, openable, lockable, locked, container';

При открытом кейсе на команду "осмотреть кейс" выводится: "В кейсе находится предмет."
when_open игнорируется.

**Comment by gl00my** [comment]
Не баг. Если объект контейнер и он открыт, то стандартное поведение движка -- показать его содержимое. when_open в таком случае используется только при описании объекта в сцене.
