### ISSUE TITLE
Загрузка снапшота ломает транскрипт

### ISSUE THREAD

**Issue by Oreolek** [instead-hub/metaparser#7]
Транскрипт ненавидит загрузку снапшотов. При загрузке он начинает записывать заново всё, что произошло к настоящему моменту, и в логах очень сложно разобраться. Причём в логах оказываются действия, которые были отменены загрузкой снапшота.

Что должно быть:
- транскрипт не должен записывать дважды то, чего даже не произошло
- хорошо бы добавить какую-нибудь разделительную линию "ЗАГРУЗКА СНАПШОТА" в транскрипт

Прилагаю минимальный пример для проверки. Как проверять:

* > транскрипт
* (сделать что угодно, например, осмотреть комнату или предметы)
* > нажать на кнопку
* все проделанные действия будут повторяться в транскрипте дважды, хотя загрузка их отменила

[transcript.zip](https://github.com/instead-hub/metaparser/files/6336720/transcript.zip)

**Comment by gl00my** [comment]
Игрок осмотрел машину и нажал на кнопку. Получил такой лог.
```
<b>> транскрипт да</b>
Logging is enabled: /home/peter/mnt/sda6/peter/Devel/instead/games/trans/log000.txt

> осмотреть машину

<b>> осмотреть машину</b>
Маленький пьедестал с надписью «Машина времени однонаправленная». На пьедестале находится переключатель, который указывает на положение «ВЫКЛ».

> нажать на кнопку

<b>> нажать на кнопку</b>
Реальность немного расплывается… а затем собирается воедино.

<b>Комната</b>

Описание комнаты. 

Здесь находится машина времени.

```
В логе присутствуют именно те команды, которые я выполнил. Не понимаю, в чём суть проблемы? Какое ожидаемое содержание лога?

**Comment by gl00my** [comment]
Если речь о том, что транскрипт должен стереть часть лога, то это не ожидаемое поведение.

**Comment by Oreolek** [comment]
ок, был неточен: в действиях нужно хотя бы раз `осмотреть комнату`. Именно это ломает транскрипт (но не должно)

**Comment by gl00my** [comment]
Нельзя записывать снапшоты и вообще менять состояние мира из dsc.
Один раз или не один, это не так точка, в которой это делать безопасно и работу я не могу гарантировать. Если перенести снапшот в enter, то как буд-то всё работает нормально.

**Comment by gl00my** [comment]
P.S. visited не срабатывает, вероятно потому что в неё никто не делал walk, а она просто являлась стартовой комантой.

**Comment by gl00my** [comment]
Пока такое наблюдение:
1) с транскриптом это не связано
2) if not visited() работает каждый ход
3) если перенести создание снапшота в eneter или вместо visited написать if s:once() то работает
4) пока бага не вижу

Посмотри, если всё так, то можно закрыть.

**Comment by Oreolek** [comment]
Ну значит, надо как-то добавить в доке что `visited` не работает в стартовой комнате.

> Если перенести снапшот в enter…
`enter` опять же не выполняется в стартовой комнате, потому что туда никто не входит. Без создания снапшота не происходит загрузки. Можно легко проверить, добавив чего-нибудь что можно `взять`.

`once` решает задачу, спасибо.

**Comment by gl00my** [comment]
visited в любом случае не сработало бы, потому что в dsc он или уже true (и всегда true) или не работает. Подробности я проверю потом.

Вообще,я в enter перенёс и оно работает. enter вызывается по-моему в любом случае, если игра стартует.
