### ISSUE TITLE
Статусы предметов в инвентаре

### ISSUE THREAD

**Issue by goraph** [instead-hub/metaparser#9]
Если предмет светит, статус не отображается вообще, желательно сделать по анологии с "открыт/закрыт", например "лампа (светит)".
Также - если у предмета два статуса (например, открыт и надет), выводится только один. Неплохо бы выводить все, например "сумка (открыта и надета)".

**Comment by gl00my** [comment]
Сделал. Правда, всё ещё думаю насчет целесообразности показа switchable и light, поэтому добавил такую таблицу, которую автор игры может поменять у себя сам:
```
mp.detailed_attr = {
	{ 'worn' },
	{ 'open', 'openable'},
--	{ 'on', 'switchable'},
--	{ 'light' }
}
```
Соответственно, в игре можно управлять показываемыми уточнениями. Функции mp.msg.HAS_XXX содержат информацию об аттрибуте. Например mp.msg.HAS_LIGHT вернёт "светится"
